#!/bin/bash
# ============================================================
#  Open the Wokwi simulation in your browser
#  Run: bash open_wokwi.sh
# ============================================================

WOKWI_DIR="$(cd "$(dirname "$0")/wokwi" && pwd)"

echo ""
echo "╔══════════════════════════════════════════════╗"
echo "║   🔌 Wokwi Simulation Launcher               ║"
echo "║   Smart Road Hazard Detection System         ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Opening Wokwi ESP32 project creator..."
echo ""

# Open Wokwi new ESP32 project page
open "https://wokwi.com/projects/new/esp32"

echo "📋 INSTRUCTIONS — Follow these steps in the browser:"
echo ""
echo "  STEP 1: Wokwi will open a new ESP32 project"
echo ""
echo "  STEP 2: Replace sketch.ino content"
echo "    → Click on 'sketch.ino' tab in the editor"
echo "    → Select ALL text (Cmd+A) and DELETE it"
echo "    → Open this file and copy everything:"
echo "      $WOKWI_DIR/sketch.ino"
echo "    → Paste into the Wokwi editor"
echo ""
echo "  STEP 3: Replace diagram.json"
echo "    → Click the small arrow next to 'sketch.ino'"
echo "    → Select 'diagram.json'"
echo "    → Select ALL (Cmd+A) and DELETE"
echo "    → Open this file and copy everything:"
echo "      $WOKWI_DIR/diagram.json"
echo "    → Paste into the diagram editor"
echo ""
echo "  STEP 4: Add libraries"
echo "    → Click the library icon (book icon) on the left sidebar"
echo "    → Search and add: 'Adafruit SSD1306'"
echo "    → Search and add: 'Adafruit GFX Library'"
echo ""
echo "  STEP 5: Run the simulation"
echo "    → Click the green ▶ Play button"
echo "    → The OLED will show 'Calibrating...'"
echo "    → After calibration, drag the HC-SR04 slider to test:"
echo "        Slider 45cm  → Serial prints POTHOLE,DEEP,..."
echo "        Slider 8cm   → Serial prints SPEEDBREAKER,..."
echo "        Slider 20cm  → Serial prints NORMAL"
echo ""
echo "  STEP 6: Connect to bridge.py (optional)"
echo "    → Copy serial output from Wokwi"
echo "    → In terminal: python bridge.py --mode stdin"
echo "    → Paste the serial lines"
echo ""
echo "═══════════════════════════════════════════════"
echo "  Files are ready at: $WOKWI_DIR"
echo "═══════════════════════════════════════════════"
